### ISSUE TITLE
User-Agent

### ISSUE THREAD

**Issue by ShayneP** [slince/shopify-api-php#1]
This is a great library, we want to track how many people are using it in the Shopify ecosystem.

Would you be able to replace the guzzle `User-Agent` with a unique one, so that we can track usage? Thanks for this contribution, hugely valuable!

**Comment by slince** [comment]
Hi, this is still an experimental package. At present, I can confirm that it is used in our company's project.

**Comment by ShayneP** [comment]
This is one of the best packages publicly available right now, and we want to link to it in our documentation. Is that okay with you?

**Comment by slince** [comment]
Yeah,  that sounds great！

**Comment by maximzasorin** [comment]
@slince Hello, do we still need this issue? You added an user-agent in this commit: https://github.com/slince/shopify-api-php/commit/0db4905cb2b9894fd3b83e55e1ffed4f938aacf7
