### ISSUE TITLE
composer problem

### ISSUE THREAD

**Issue by wennima** [slince/shopify-api-php#10]
Hi, when I install this api via composer,installation failed with a problem:
   
Problem 1
    - The requested package slince/shopify-api-php No version set (parsed as 1.0
.0) is satisfiable by slince/shopify-api-php[No version set (parsed as 1.0.0)] b
ut these conflict with your requirements or minimum-stability.

Do you know how to fix this problem?

**Comment by wennima** [comment]
Thanks for your reply !
I got same problem using the command, not sure if that was composer cache or anything else, then I try

`composer require slince/shopify-api 2.0.3`

and it works. And I could successfully fetch products on my test store by running example scripts.
Thanks!

**Comment by slince** [comment]
feel free to let me know if you have any questions. 😃
