### ISSUE TITLE
Search orders by email address

### ISSUE THREAD

**Issue by krafi** [slince/shopify-api-php#14]
Hi,
I have been trying to use Order Manager to search orders by email address. But in return i am getting all orders instead of the one's for that email address. Same is happening if i try to find a customer using email.

$customer = $client->getCustomerManager()->findAll(['email' => 'abc@xyz.com']);
$orders = $client->getOrderManager()->findAll(['email' => 'abc@xyz.com']);

Not sure if i am passing the wrong parameters to the findAll function.

:(

**Comment by maximzasorin** [comment]
Hello, to filter orders, as well as to filter customers, you can only use the parameters that Shopify provides.

You can see the list of parameters here:
https://help.shopify.com/en/api/reference/orders/order#index
https://help.shopify.com/en/api/reference/customers/customer#index

There is no email parameter among them.

**Comment by slince** [comment]
> I have been trying to use Order Manager to search orders by email address

You can not filter orders with `email` or `customer`. this is not be supported.  

you can refer to the link above.

**Comment by krafi** [comment]
Well this is not true, We can do this by simple call using following link
https://abc.myshopify.com/admin/orders/search.json?query=abc@xyz.com

I was looking for this option is this PHP wrapper.

Thanks

**Comment by maximzasorin** [comment]
@krafi This is not a part of REST Admin API.
