### ISSUE TITLE
List of Collects for one product

### ISSUE THREAD

**Issue by nitromedia** [slince/shopify-api-php#17]
So i'm trying to use your API Client to list all the collections related to a product.

According to the docs of Shopify it should be done like this :
GET admin/collects.json?product_id=XXXXXXX

I tried a couple of methods from the manager, but nothing seems to work.

$collect = $client->getCollectManager()->find(XXXXXX); (don't work)
$collect = $client->get('collects.json?product_id=XXXXXX'); (list results, but not the one i'm expecting)

**Comment by slince** [comment]
Method  `find` is used to get one entity by its id; 

if you want get  entity collection, you should use `findAll`":

```php
 $collects = $client->getCollectManager()->findAll(['product_id' => xxx]);
```
if you want to get raw data;

```php
 $collects = $client->getCollectManager()->get('collects', ['product_id' => xxx]);

print_r($collects);
```
argument 1 is a resource identiter; 

there is a example about product in `README.md`; you can reference it

**Comment by nitromedia** [comment]
Thank you very much !!! So simple ;)

Also there seems to be nothing about inventory Level, will it be added eventually ?

**Comment by slince** [comment]
> Also there seems to be nothing about inventory Level, will it be added eventually ?

is there a help doc url?

**Comment by nitromedia** [comment]
https://help.shopify.com/en/api/reference/inventory

**Comment by slince** [comment]
see 2.2.0
