### ISSUE TITLE
Metafields

### ISSUE THREAD

**Issue by KDederichs** [slince/shopify-api-php#18]
Hey,

maybe I'm just not seeing it but am I able to receive an manipulate metafields with your API?

According to https://help.shopify.com/en/api/reference/products/product_variant Variants have a Metafield

There also seems to be a Metafields endpoint https://help.shopify.com/en/api/reference/metafield
but no Metafield manager.

Best regards

**Comment by slince** [comment]
hi, this package does not contain the full shopify resource manager.  Some resources are rarely used; you can use a simple way `get/post/put/delete` to manipulate  "metafield"

```php
$metafields = $client->get('metafields', ['since_id' => xxxx])
$metafields = $client->get('products/123xxx/metafields')
```

of course. If you have free time, you can also submit a pr to improve this 😄 .
