### ISSUE TITLE
Delay next request not works

### ISSUE THREAD

**Issue by maximzasorin** [slince/shopify-api-php#2]
Hello, your lib is awesome, but the delay before the next request in `sendRequest` looks useless. I create and run next code for example:

```php
$client = ...;

$shopManager = $client->getShopManager();
$index = 1;

while (true) {
    print ($index++) . ' ' . $shopManager->get()->getName() . "\n";
}
```

And it throws `429 Too Many Requests` exception after ~57 requests.

**Comment by slince** [comment]
Hi, i have tested 176 requests and have not yet finished; Can you tell me what kind of credentials you are using, public or private?

157 SNSELL               
158 SNSELL               
159 SNSELL               
160 SNSELL               
161 SNSELL               
162 SNSELL               
163 SNSELL               
164 SNSELL               
165 SNSELL               
166 SNSELL               
167 SNSELL               
168 SNSELL               
169 SNSELL               
170 SNSELL               
171 SNSELL               
172 SNSELL               
173 SNSELL               
174 SNSELL               
175 SNSELL               
176 SNSELL               
^C

**Comment by maximzasorin** [comment]
I using public credentials. On my local machine I can not get problem, but on my DO droplet it occurs stable on 50–70 requests. Should the solution in `sendRequest` should work correctly with [call limit](https://help.shopify.com/api/getting-started/api-call-limit) from docs?

**Comment by slince** [comment]
Maybe the pause time is too short; can you modify sleep time in your vendor and try again?
[https://github.com/slince/shopify-api-php/blob/master/src/Client.php#L305](https://github.com/slince/shopify-api-php/blob/master/src/Client.php#L305)

For example:
```php
  usleep(1000000 * rand(3, 10));
```

**Comment by maximzasorin** [comment]
I modify sleep to:
```php
usleep(1000000 * rand(3, 10));
```
And it works correctly on more than 500 requests.

**Comment by maximzasorin** [comment]
@slince Will this fix be added to the release?

**Comment by slince** [comment]
of course. give me some time. 😈
