### ISSUE TITLE
locationID in fulfillment object is missing

### ISSUE THREAD

**Issue by jonathangreco** [slince/shopify-api-php#29]
I don't know if it's a mistake or if it's relative to older version of shopify API but locationId is missing.

This is disturbing because we don't know where to send the order without it.

here is a snapshot of what is returned from the API (findAll on orders)
![Capture d’écran 2019-05-02 à 14 24 53](https://user-images.githubusercontent.com/1587180/57075092-1610fa00-6ce6-11e9-9cf1-c88567451c2a.png)

**Comment by jonathangreco** [comment]
@slince Hi, there is a conflict but this is a really needed feature to me :) hope it will be merged and released soon.

**Comment by slince** [comment]
Ok, I will try to resolve these conflicts.
