### ISSUE TITLE
Delete product

### ISSUE THREAD

**Issue by nezaboravi** [slince/shopify-api-php#31]
As per documentation, to delete product do this:

$client->getProductManager()->delete(12800);

However, php unit test throws this:

$this->shopifyClient->getProductManager()->delete(3573905391715);
Error : Call to undefined method Slince\Shopify\Manager\Product\ProductManager::delete()
I have been looking into ProductManager and Product classes and could not find delete() method.

**Comment by maximzasorin** [comment]
@nezaboravi 

Hello, this is an error in the documentation, to remove product, you should use the remove method:

```
$client->getProductManager()->remove(3573905391715);
```

A list of all ProductManager methods can be found here:

https://github.com/slince/shopify-api-php/blob/master/src/Manager/Product/ProductManagerInterface.php

**Comment by slince** [comment]
This is a mistake. Thanks @maximzasorin  for helping to fix this.
