### ISSUE TITLE
Search operation with query parameters not working

### ISSUE THREAD

**Issue by chintankotadia** [slince/shopify-api-php#33]
Hello,

Search operation for customer with query parameters always returns all the customers without any filtering.

Following is the example:-

`$customer = $client->getCustomerManager()->search(['email:email@example.com']);`

Am I missing anything in this one? This is forum post which I am following https://community.shopify.com/c/Shopify-APIs-SDKs/Find-a-Customer-by-Email-via-API-Call/td-p/141661

Thank you!

**Comment by slince** [comment]
hello, you shoud try this:
```php
$customers = $client->getCustomerManager()->search(['email' => 'email@example.com']);
```

**Comment by chintankotadia** [comment]
@slince : I did but same problem. :)

**Comment by slince** [comment]
hello, this will be fixed in furture version

**Comment by maximzasorin** [comment]
@chintankotadia 

In the [search method](https://help.shopify.com/en/api/reference/customers/customer#search) there is only `query` parameter, you need to pass a string to it.

Try this:

```php
$customers = $client->getCustomerManager()->search([
    'query' => 'email:address@example.com'
]);
```

**Comment by chintankotadia** [comment]
@maximzasorin : Thanks, it did work!

**Comment by larsjanssen6** [comment]
Not working for me.
