### ISSUE TITLE
PUT (update) does not work

### ISSUE THREAD

**Issue by deventerKL** [slince/shopify-api-php#34]
$ordersProcessing = $client->getOrderManager()->update(1090684911701, [
    // set data
    'financialStatus' => 'paid',
]);

Does not work. Neither does 

     'financial_status' => 'paid',

**Comment by slince** [comment]
hello，Is there any error message? Does your app has permission to operate on orders?

**Comment by deventerKL** [comment]
No, sadly no error message. It seems to work fine, but doesn't have any effect on the status. And yes, the app has read/write permissions on orders.

**Comment by slince** [comment]
@deventerKL   According to this article, `financial_status` cannot be updated  https://community.shopify.com/c/Shopify-APIs-SDKs/Change-Status-of-Order/td-p/261839
https://help.shopify.com/en/api/reference/orders/order#update

![image](https://user-images.githubusercontent.com/3785826/59492775-3e327200-8ebc-11e9-96d2-56d7baa9bc40.png)

 Maybe you should try `transaction`
