### ISSUE TITLE
Vendor dependancies, quite substantial.

### ISSUE THREAD

**Issue by louiswalch** [slince/shopify-api-php#37]
Just wanting to check, have you confirmed that all the vendor libraries loaded through 

> composer require slince/shopify-api-php

 are required? There seems to be much more then would be expected for a simple API library - 7.8MB.

**Comment by slince** [comment]
Hello, I noticed this too, but there is no better way to do it. We need `JMS /serializer`, but I have to say this library has too many dependencies; `Doctrine/XXX` and `hoa/ XXX`; I'll try symfony/serialzier if I can. But this is obviously not the best time to do this.

**Comment by slince** [comment]
fixed in  v3.x
