### ISSUE TITLE
Order model does not contain customer object/property

### ISSUE THREAD

**Issue by phena109** [slince/shopify-api-php#38]
I have used the `OrderManager` to get an order and in the API doc it says we will have the customer property but there is no function called `getCustomer` in the `Order` model I retrieved.

In the end I have fallback to use the basic CRUD to get the order detail again and extract the customer information.

Can you please add the customer bit in? Thanks so much
D.

**Comment by slince** [comment]
This will be added in the next release

**Comment by phena109** [comment]
Just an update.

For some reason I have cleaned up my vendor folder and redownload everything as well as the cache folder the library created. I then keep getting exception ` You must define a type for Slince\Shopify\Manager\Order\Order::$customer. `

After extensive check, I realised it at lease didn't throw any exception was because I have been naughty and changed some of the config file and that's why at the very least no exception. But as I load up everything from scratch, I get the issue and I am sure it happens repeatedly. Later I found out what I have changed is the YAML file at `protected/vendor/slince/shopify-api-php/config/serializer/Manager.Order.Order.yml`. I just need to append the following and the customer property will at least show up as plain array with the right information.

```
        customer:
            type: array
```

While this is not ultimately what I want and I can just move 1 step further to create the class for customer, I don't think I have much time to do so. This is just a quick info for you to put in the code so you can at least avoid some unwanted exceptions as well as sort of serve the customer content in the order object.

Hope this help,
D

**Comment by slince** [comment]
fixed;  you can access customer `$order->getCustomer(); `
// instance of Slince\Shopify\Manager\Customer\Customer
