### ISSUE TITLE
How I can get header pagination for searches.

### ISSUE THREAD

**Issue by camilo300792** [slince/shopify-api-php#45]
```
#...
Link: "<https://{shop}.myshopify.com/admin/api/{version}/products.json?page_info={page_info}&limit={limit}>; rel={next}, <https://{shop}.myshopify.com/admin/api/{version}/products.json?page_info={page_info}&limit={limit}>; rel={previous}"
#...
```

The link header includes a rel parameter, where relation-types describes the relation of the linked page to the current page of results. The value can either be previous or next.

The URL in the link header can include up to two parameters:

    page_info: A unique ID used to access a certain page of results. The page_info parameter can't be modified and must be used exactly as it appears in the link header URL.
    limit: The maximum number of results to show on the page.

A request that includes the page_info parameter can't include any other parameters except for limit. If you want your results to be filtered by other parameters, then you need to include those parameters in the first request you make.

**Comment by camilo300792** [comment]
``` php
protected function buildUrl($resource)
{
        # return sprintf('https://%s/admin/%s.json', $this->shop, $resource);
        return sprintf('https://%s/admin/api/2019-10/%s.json', $this->shop, $resource);
}
```

**Comment by slince** [comment]
see #46
