### ISSUE TITLE
Trying to update total tax

### ISSUE THREAD

**Issue by tone10** [slince/shopify-api-php#49]
I am trying to send total tax to my order.  Am I missing something.  

Here is what I have for total tax for my order:
$order = $client->getOrderManager()->put('$order_id', [
    "total_tax"  => "$total_tax",
]);

**Comment by slince** [comment]
Yes,  `https://github.com/slince/shopify-api-php/blob/master/src/Manager/Order/OrderManagerInterface.php`   You're using a method that doesn't exist; You can check the methods provided by the manager before you use them
