### ISSUE TITLE
How get variant Cost

### ISSUE THREAD

**Issue by zerdmer** [slince/shopify-api-php#56]
How get variant Cost?

$variant->getCost(); doesn't work, some idea? thanks!

**Comment by zerdmer** [comment]
ok, i got it, but now:

$x=$client->getInventoryItemManager()->find($ProductVariantInventoryId);
echo $x->getCost(); // get the cost
echo $x->setCost(1.1); // doesn't work

**Comment by zerdmer** [comment]
even with $x->setCost("1.1") or $x->setCost("1,1") still doesn't work

**Comment by zerdmer** [comment]
THIS WORKS:
$client->getInventoryItemManager()->update($ProductVariantInventoryId, [
                        "cost" => $NewCost
                    ]);
But the ->setCost should work, and it doesn't

**Comment by maximzasorin** [comment]
@zerdmer 

All models in the library are simple value objects. The design of the library does not assume that calling the setter will perform a request to the API and change the value on the side of Shopify. The correct way to update the value is to use the update method.
