### ISSUE TITLE
Auto limit doesn't work well

### ISSUE THREAD

**Issue by baorv** [slince/shopify-api-php#64]
I got this error when using this package to fetch order information

`429 Too Many Requests` response: {"errors":"Exceeded 0 calls per second for api client. Reduce request rates to resume uninterrupted service." `

**Comment by imandydoan** [comment]
How can I handle error 429 in this package? @slince

**Comment by slince** [comment]
Hello; You can catch this exception and do something else;

```php

try {
    $currentProducts = $pagination->current(); //current page

    while ($pagination->hasNext()) {
        $nextProducts = $pagination->next();
    }
} catch (Slince\Shopify\Exception\ClientException $e) {
       dump($e);
}
```

**Comment by imandydoan** [comment]
I think that error 429 should be implemented in this package. I see that you implement it in this line: https://github.com/slince/shopify-api-php/blob/master/src/Client.php#L344

But I still got this error.

**Comment by baorv** [comment]
As you can see this package from [bold-commerce/bold-shopify-toolkit](https://github.com/bold-commerce/bold-shopify-toolkit). 

https://github.com/bold-commerce/bold-shopify-toolkit/blob/master/src/Services/Client.php#L305

https://github.com/bold-commerce/bold-shopify-toolkit/blob/master/src/Support/ShopifyApiHandler.php

**Comment by slince** [comment]
fixed
