### ISSUE TITLE
Asset manager

### ISSUE THREAD

**Issue by maximzasorin** [slince/shopify-api-php#7]
Hello, I tried using [AssetManager](https://github.com/slince/shopify-api-php/blob/master/src/Manager/Asset/AssetManagerInterface.php) to get and edit an asset of the theme, but looks like it does not work, I can not get and edit single asset.

Asset resource API stands apart from other: https://help.shopify.com/en/api/reference/online_store/asset, it does not have id, but identified by the key, asset does not have particular method for creating resources (only for create or update), asset does not have `/count` resource. I think we need to remake AssetManager.

**Comment by slince** [comment]
thk. it is my mistake; I didn't use this feature in my project, so I didn't verify it.

**Comment by slince** [comment]
I have released a new version.
