### ISSUE TITLE
Composer install problem

### ISSUE THREAD

**Issue by stealthpro** [slince/shopify-api-php#80]
Lumen 7.
Problem:
`  Problem 1`
`    - Installation request for slince/shopify-api-php ^2.5 -> satisfiable by slince/shopify-api-php[2.5.0].`
`    - Conclusion: remove doctrine/inflector 2.0.1`
`    - Conclusion: don't install doctrine/inflector 2.0.1`
`    - slince/shopify-api-php 2.5.0 requires doctrine/inflector ^1.0 -> satisfiable by doctrine/inflector[1.0.x-dev, 1.1.x-dev, 1.2.x-dev, 1.3.1, 1.3.x-dev, 1.4.0, 1.4.1, 1.4.x-dev, v1.0, v1.0.1, v1.1.0, v1.2.0, v1.3.0].`
`    - Can only install one of: doctrine/inflector[1.1.x-dev, 2.0.1].`
`    - Can only install one of: doctrine/inflector[1.2.x-dev, 2.0.1].`
`    - Can only install one of: doctrine/inflector[1.3.1, 2.0.1].`
`    - Can only install one of: doctrine/inflector[1.3.x-dev, 2.0.1].`
`    - Can only install one of: doctrine/inflector[1.4.0, 2.0.1].`
`    - Can only install one of: doctrine/inflector[1.4.1, 2.0.1].`
`    - Can only install one of: doctrine/inflector[1.4.x-dev, 2.0.1].`
`    - Can only install one of: doctrine/inflector[v1.1.0, 2.0.1].`
`    - Can only install one of: doctrine/inflector[v1.2.0, 2.0.1].`
`    - Can only install one of: doctrine/inflector[v1.3.0, 2.0.1].`
`    - Can only install one of: doctrine/inflector[1.0.x-dev, 2.0.1].`
`    - Can only install one of: doctrine/inflector[v1.0, 2.0.1].`
`    - Can only install one of: doctrine/inflector[v1.0.1, 2.0.1].`
`    - Installation request for doctrine/inflector (locked at 2.0.1) -> satisfiable by doctrine/inflector[2.0.1].`

**Comment by slince** [comment]
This issue has been fixed in 2.5.1
