### ISSUE TITLE
deprecated Inflector

### ISSUE THREAD

**Issue by Katanji** [slince/shopify-api-php#81]
Laravel              - 5.8
php                    - 7.3
shopify-api-php - 2.5

when i use tinker and do some requests, there shows many warnings like:
PHP Deprecated:  The "Doctrine/Common/Inflector/Inflector::pluralize" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API. in .../vendor/doctrine/inflector/lib/Doctrine/Common/Inflector/Inflector.php on line 261

shopify-api-php require :
"doctrine/inflector": "^1.0"

maybe its time to "^2.0" )

**Comment by slince** [comment]
This issue has been fixed in 2.5.1
