### ISSUE TITLE
500 Inflector not found

### ISSUE THREAD

**Issue by schevgeny** [slince/shopify-api-php#82]
Updating slince/shopify-api-php dev-master (8a3fde2 => fab750f):

`Error: Class 'Doctrine\Common\Inflector\Inflector' not found in /home/shopify_core/vendor/slince/shopify-api-php/src/Client.php:184`

new composer update crashed my project!

**Comment by slince** [comment]
You should avoid using the Master branch, this is an unstable version 😄
