### ISSUE TITLE
getVariantManager()->find() not working

### ISSUE THREAD

**Issue by sharaxco** [slince/shopify-api-php#83]
Hi

i want to use this function for find product with VariantID but not worked.

> $credential = new \Slince\Shopify\PrivateAppCredential($ConfVal->key, $ConfVal->password, $ConfVal->shared_secret);
$client = new \Slince\Shopify\Client($credential, $ConfVal->url, [
      'metaCacheDir' => './Shopifytmp/'.$ConfVal->key // Metadata cache dir, required
]);
dd($client->getVariantManager()->findAll());

Response:
>Slince\Di\Exception\NotFoundException
There is no definition named "variants"

**Comment by slince** [comment]
use `getProductVariantManager`
