### ISSUE TITLE
No "ID" attribute set for Order and Order items

### ISSUE THREAD

**Issue by ReyazBeigh** [slince/shopify-api-php#85]
Trying to get ID attribute for Order and Order line items, it gives, tried to debug further, and looks like it is not set. Not sure if it is an issue or am I doing anything wrong

**Comment by slince** [comment]
hello, can you try again with v2.4.x

**Comment by ReyazBeigh** [comment]
Hi @slince 

Added 2.4.0 and it is still the same

**Comment by slince** [comment]
Hello, can you try again using 2.5.2, we realized that it may be caused by the different versions of jms/serializer

**Comment by ReyazBeigh** [comment]
Hi @slince 

We will try that out soon. Thanks for the update.

**Comment by slince** [comment]
If the problem is not resolved, please feel free to create a new issue
