### ISSUE TITLE
Conflict with latest guzzlehttp/guzzle:7.0.1

### ISSUE THREAD

**Issue by shresthanimish** [slince/shopify-api-php#88]
The latest version of laravel (v8.0) requires guzzlehttp/guzzle:7.0.1. However, slince/shopify-api-php only satisfiable upto 6.x.

  Problem 1
    - slince/shopify-api-php 2.5.1 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - slince/shopify-api-php 2.5.0 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - slince/shopify-api-php 2.5.1 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for slince/shopify-api-php ^2.5 -> satisfiable by slince/shopify-api-php[2.5.0, 2.5.1].

**Comment by rafi73** [comment]
Facing the similar issue! Did you find any solution for this?

**Comment by shresthanimish** [comment]
Yes. I found out that Laravel 8 doesn't necessarily require Guzzle 7.x. V6.5 works just as well. So the trick here is to have both versions available in composer. Here is the entry I have to fix the issue:

`"guzzlehttp/guzzle": "^6.5|^7.0.1",`

**Comment by rafi73** [comment]
Thanks a lot for your prompt reply 🙏

**Comment by shresthanimish** [comment]
No problem. Hope that helped.

**Comment by rafi73** [comment]
`$ composer require slince/shopify-api-php
Using version ^2.5 for slince/shopify-api-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove guzzlehttp/guzzle 7.2.0
    - Conclusion: don't install guzzlehttp/guzzle 7.2.0
    - slince/shopify-api-php 2.5.0 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev].
    - slince/shopify-api-php 2.5.1 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^6.5.0|^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].
    - Installation request for slince/shopify-api-php ^2.5 -> satisfiable by slince/shopify-api-php[2.5.0, 2.5.1].


Installation failed, reverting ./composer.json to its original content.`

Facing this situation

**Comment by shresthanimish** [comment]
Looks like you might have previously installed guzzle 7.2 which is now in your compose.lock file. You can try copying your compose.lock file outside of your project for backup. Then remove it from your project and run composer install.
