### ISSUE TITLE
Laravel Integration not available 

### ISSUE THREAD

**Issue by Mazhariqbalfullstack** [slince/shopify-api-php#89]
Please guide me how to use in Laravel 8 version. I am unable to use in Laravel 8 version please guide me how to add and use in Laravel 8 controller..

Thank You.

**Comment by slince** [comment]
Hello, can you tell me what error you encountered

**Comment by jstoone** [comment]
I started a new Laravel 8 project on the 28 November, and your package has worked absolutely flawlessly. ❤️ 

Personally I think this issue is safe to close, as they probably solved their problem. :v:
